#!/bin/bash

# Wallpaper
nitrogen --restore

# Notification Manager
dunst &

# Compositor
picom &

# Bar
$HOME/.config/polybar/launch.sh

# Keybindinds Manager
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_radius                 8
bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config split_ratio                   0.52
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config click_to_focus                true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config focus_follows_pointer         true

bspc config normal_border_color           "#282828"
bspc config active_border_color           "#fbf1c7"
bspc config focused_border_color          "#98971a"
bspc config presel_feedback_color         "#458588"
bspc config urgent_border_color           "#cc241d"


bspc rule -a Pcmanfm desktop='^2'
bspc rule -a Google-chrome desktop='^3'
bspc rule -a code-oss desktop='^4'
bspc rule -a Vlc desktop='^5'



